NAME: 'RPC_Single_Image_Features_res50_200_p'
OUTPUT_DIR: '/media/hao/Data/RPC/single_features/'
CPU_MODE: False
COLOR_SPACE: 'RGB'
SINGLE_SIZE: (512, 512)
NETWORK: 'ClassificationNetwork'
#COMBINER: 'ClassificationCombiner'

DATASET:
  DATASET: 'RPCSingleP'
  DATA_TYPE: 'jpg'
  SINGLE_JSON: '/media/hao/Data/RPC/instances_train2019.json'
#  SINGLE_JSON: '/media/hao/Data/RPC/sample/val/150_single.json'
#  SINGLE_JSON: '/media/hao/Data/RPC/sample/sub/183_single.json'
#  SINGLE_JSON: '/media/hao/Data/RPC/cropped_val.json'
  SINGLE_ROOT: '/media/hao/Data/RPC/train2019/'
#  SINGLE_ROOT: '/media/hao/Data/RPC/cropped_val2019/'


BACKBONE:
  TYPE: 'resnet50' # resnet50_l2
  PRETRAINED: True
  #PRETRAINED_MODEL: '/data/Data/pretrain_models/resnet50.pth'

MODULE:
  TYPE: 'GMP'

TRANSFORMS:
  TRAIN_TRANSFORMS: ('normal_resize',)

TEST:
  BATCH_SIZE: 64 # 64
  NUM_WORKERS: 8 # 8
  MODEL_FILE: '/home/hao/Desktop/Counting_CodeBase/output/RPC/RPC_Single_Recognition_resnet50_200/models/1.0000_best_model.pth'