NAME: 'Check-out_attention' #
OUTPUT_DIR: '/home/hao/Desktop/Counting_CodeBase/output/RPC'
CPU_MODE: False
SHOW_STEP: 100
COLOR_SPACE: 'RGB'
CHECK_SIZE: (512, 512) # (384, 384)(256, 256)
#NETWORK: 'RPCNetwork'
NETWORK: 'RPCDomainAttentionNetwork'

DATASET:
  DATASET: 'RPCSingleFixNoSample'
  DATA_TYPE: 'jpg'
  TEST_JSON: '/media/hao/Data/RPC/instances_test2019.json'
  TEST_ROOT: '/media/hao/Data/RPC/test2019/'
#  TEST_JSON: '/media/hao/Data/RPC/instances_val2019.json'
#  TEST_ROOT: '/media/hao/Data/RPC/val2019/'
#  TEST_JSON: '/media/hao/Data/RPC/visual.json'

#  TEST_JSON: '/data/rpc/retail_product_checkout/sample/val/195_check.json'
#  TEST_JSON: '/data/rpc/retail_product_checkout/sample/150_check.json'

  SINGLE_JSON: '/media/hao/Data/RPC/single_features/RPC_Single_Image_Features_res50_l2_200/single_feature.json'
  SINGLE_ROOT: '/media/hao/Data/RPC/single_features/RPC_Single_Image_Features_res50_l2_200/features/'

  NOSAMPLE_TYPE: 'part' # [part, all, fp]
  LEVEL: 'avg' # [avg, easy, medium, hard]
#  FP_JSON: '/home/hao/Desktop/Counting_CodeBase/output/RPC/RPC_Counting_Hourglass_Domain_Attention_9_64_512/fp.json'


BACKBONE:
  TYPE: 'hourglass'
  HOURGLASS:
    NUM_BLOCKS: 1
    NUM_STACKS: 1
    SCALE: 2

TRANSFORMS:
  TRAIN_TRANSFORMS: ('normal_resize',)
  TEST_TRANSFORMS: ('normal_resize',)

TEST:
  BATCH_SIZE: 1
  NUM_WORKERS: 8
#  MODEL_FILE: '/data/ActivityNet/Counting_CodeBase/output/RPC/RPC_Counting_Hourglass_R2/models/0.7602_best_model.pth'
#  MODEL_FILE: '/data/ActivityNet/Counting_CodeBase/output/RPC/RPC_Counting_Hourglass_Adv_SingleFix_R2/models/0.7920_best_model.pth'
#  MODEL_FILE: '/home/hao/Desktop/Counting_CodeBase/output/RPC/RPC_Counting_Hourglass_Domain_Attention_9_64_512/models/0.7896_best_model.pth'
  MODEL_FILE: '/home/hao/Desktop/output/RPC/RPC_Counting_Hourglass_Domain_Attention_SS_512/models/0.8212_best_model.pth'